DETOUR_COUNT_KEY = "DETOUR_COUNT"
DETOUR_IGNORE_KEY = "DETOUR_IGNORE"
DETOUR_ACTIVE_KEY = "DETOUR_ACTIVE"
DETOUR_PREV_SETTINGS_KEY = "DETOUR_PREV_SETTINGS"

DETOUR_TARGET_DISTANCE = 130
DETOUR_TARGET_TR_X = 450
DETOUR_TARGET_BR_X = 480
DETOUR_FORCED_SIDE = 1

DEVIATION_COUNTER_CONTROL = "DeviationCounter"
