CUSTOM_OBJECT_PRIORITY = [
    ("PLACA_PARE", 1),
    ("PLACA_DESVIO", 2),
    ("PLACA_LOMBADA", 3),
]
CUSTOM_OBJECT_CODE_BY_LABEL = {label: code for label, code in CUSTOM_OBJECT_PRIORITY}
CUSTOM_OBJECT_LABEL_BY_CODE = {code: label for label, code in CUSTOM_OBJECT_PRIORITY}

__all__ = [
    "CUSTOM_OBJECT_PRIORITY",
    "CUSTOM_OBJECT_CODE_BY_LABEL",
    "CUSTOM_OBJECT_LABEL_BY_CODE",
]
