FLAGS_TO_IGNORE = ["SEND_DATA", "WEBVIEW", "NEW_PID"]

UI_PERSIST_FLAGS = [
    "WEBVIEW",
    "SECURITY_COM",
    "SENDER_COM",
    "LANE_SOURCE",
    "OBJECT_SOURCE",
    "DETECTED_CAMERAS",
    "NEW_PID",
    "SEND_DATA"
]