from typing import Protocol


class SettingsStore(Protocol):
    def load(self, file_path, update_target_if_exists=None): ...
    def save(self, data, file_path): ...
    def update(self, updates: dict, path: str, only_existing_keys: bool = False): ...


class SerialSender(Protocol):
    def ensure_connection(self, cooldown: float = 2.0) -> bool: ...
    def send(self, data, verbose=False): ...
    def receive(self): ...
    def change_port(self, new_port, send_data, open_for_receive): ...
    def close(self): ...


class VideoSourceManager(Protocol):
    @property
    def current_source(self): ...
    def open_video_source(self, lane_queue, shared_controls, logger, safe_stop_cb, cooldown: float = 2.0): ...
    def ensure_video_source(
        self,
        video_processor,
        requested_source,
        queue,
        shared_controls,
        logger,
        safe_stop_cb,
        cooldown: float = 2.0,
    ): ...


class LoggerPort(Protocol):
    def info(self, message: str): ...
    def warning(self, message: str): ...
    def error(self, message: str): ...
