from typing import Any, Protocol


class SettingsStore(Protocol):
    def load(self, file_path, update_target_if_exists=None): ...
    def save(self, data, file_path): ...
    def update(self, updates: dict, path: str, only_existing_keys: bool = False): ...


class SerialSender(Protocol):
    def ensure_connection(self, cooldown: float = 2.0) -> bool: ...
    def send(self, data, verbose=False): ...
    def close(self): ...


class VideoSource(Protocol):
    def get_frame(self) -> Any: ...
    def release(self) -> None: ...
    def is_frame_open(self) -> bool: ...
