import multiprocessing as mp
import cv2 as cv
import time

from controllers.pid_controller import PIDController
from controllers.lane_detector import LaneDetector
from controllers.serial_comm import SerialCommunicator
from processing.video_processor import VideoProcessor
from processing.priorities_processor import set_process_priority
from processing.warp_perspective_processor import bird_eye
from processing.object_detection_processor import ObjectDetector
from utils.display import draw_overlays, create_main_window
from processing.multiprocessing.object_detector_trackbar import object_detector_trackbar_process
from utils.real_time_trackbars import create_control_window, get_trackbar_values
from utils.buttons import create_tkinter_controls


from processing.multiprocessing.data_sender_multiprocess import data_sender_process
from processing.multiprocessing.lane_detection_multiprocess import lane_detection_process
from processing.multiprocessing.object_detector_multiprocess import object_detection_process
from processing.multiprocessing.security_multiprocess import security_process
from processing.multiprocessing.object_detector_trackbar import object_detector_trackbar_process
from utils.buttons import create_tkinter_controls