auto_generated: true
base_dataset: dataset
models:
- name: PLACA_PARE
  dataset: dataset\PLACA_PARE
  classes:
  - PLACA_PARE
  class_ids:
  - 0
  output: yolo_runs/PLACA_PARE
  val_ratio: 0.2
  train: {}
- name: PLACA_LOMBADA
  dataset: dataset\PLACA_LOMBADA
  classes:
  - PLACA_LOMBADA
  class_ids:
  - 1
  output: yolo_runs/PLACA_LOMBADA
  val_ratio: 0.2
  train: {}
- name: PLACA_DESVIO
  dataset: dataset\PLACA_DESVIO
  classes:
  - PLACA_DESVIO
  class_ids:
  - 2
  output: yolo_runs/PLACA_DESVIO
  val_ratio: 0.2
  train: {}
