from src.application.usecases.data_sender_multiprocess import data_sender_process
from src.application.usecases.lane_detection_multiprocess import lane_detection_process
from src.application.usecases.object_detector_multiprocess import object_detection_process
from src.application.usecases.security_multiprocess import security_process
from src.application.usecases.manual_mode_multiprocess import manual_video_process

from src.infrastructure.adapters.web_server.app import start_flask_server
from src.infrastructure.adapters.display.ui.main_app import MainApp
from src.infrastructure.logging.logger import Logger
from src.infrastructure.constants.services_constants.process_constants import shutdown_endpoint

import requests
import multiprocessing as mp