from src.infrastructure.adapters.calibration.config_persistence import load_calibration
from src.infrastructure.adapters.interface.flags_init import setup_flag_interface

import multiprocessing as mp

from src.infrastructure.utils.shared_controls_init_processor import init_shared_controls, print_initial_flags
from src.application.services.process_service import create_processes