from src.infrastructure.adapters.video.video_utility_process import switch_video_source
from src.infrastructure.logging.logger import Logger
from src.infrastructure.services.manual_mode_service import publish
import time
from src.infrastructure.utils.update_time_processor import update_processing_time