from src.infrastructure.adapters.calibration.calibration_repository import load_data
from src.infrastructure.adapters.interface.setup_flags_init_ui import setup_flag_interface

import multiprocessing as mp

from src.infrastructure.utils.shared_controls_init_processor import init_shared_controls, print_initial_flags
from src.application.services.process_service import create_processes
from src.infrastructure.constants.ui_constants.file_constants import CALIBRATION_FILE, DEFAULTS_FILE